ParqueWeb/Models/ErrorViewModel.cs
using System;

namespace ParqueWeb.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

ParqueWeb/Controllers/AdministradorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace ParqueWeb.Controllers
{
    public class AdministradorController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

ParqueWeb/Controllers/CompraController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using ParqueBLL;

namespace ParqueWeb.Controllers
{
    public class CompraController : Controller
    {
        private readonly ParqueContext db;
        FachadaParque fachada;

        public IActionResult Index()
        {
            Passaporte novo = new Passaporte() { DataInicial = DateTime.Now };

            return View(novo);
        }

        [HttpGet]
        public IActionResult Orcar()
        {
            Passaporte novo = new Passaporte() { DataInicial = DateTime.Now };

            return View(novo);

        }

        [HttpPost]
        public IActionResult Orcar(Passaporte pass)
        {
            List<Passaporte> passa = new List<Passaporte>();


            passa.Add(new Passaporte { NomeCliente = "teste", ValorTotal = 100   });

            return View("Orcar", passa);

        }

        [HttpGet]
        public IActionResult ConfirmaCompra()
        {
            return View();

        }
    }
}

ParqueWeb/Controllers/EntradaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace ParqueWeb.Controllers
{
    public class EntradaController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

ParqueWeb/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using ParqueWeb.Models;

namespace ParqueWeb.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

ParqueWeb/Views/Administrador/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

ParqueWeb/Views/Compra/ConfirmaCompra.cshtml
@model ParqueBLL.Passaporte

@{
    ViewData["Title"] = "ConfirmaCompra";
}

<h1>ConfirmaCompra</h1>

<h4>Passaporte</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        
            
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ParqueWeb/Views/Compra/Index.cshtml
@model ParqueBLL.Passaporte
@{
    ViewData["Title"] = "Index";
}

<h1>Compra de Ingressos</h1>

<h4 align-center>Preencha os campos abaixo: </h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Index">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="NomeCliente" class="control-label"></label>
                <input asp-for="NomeCliente" class="form-control" />
                <span asp-validation-for="NomeCliente" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DataInicial" class="control-label"></label>
                <input asp-for="DataInicial" class="form-control" />
                <span asp-validation-for="DataInicial" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NroDias" class="control-label"></label>
                <input asp-for="NroDias" class="form-control" />
                <span asp-validation-for="NroDias" class="text-danger"></span>
            </div>
            <div class="form-group" action="/action_page.php" method="get">
                <input type="checkbox" name="Universitario" value="Universtario"> Universtario<br>
                <input type="checkbox" name="Idoso" value="Idoso"> Idoso<br>
                <input type="checkbox" name="PagueBem" value="PagueBem"> Cartão Pague Bem<br>
                <input type="checkbox" name="SeguroGarantido" value="SeguroGarantido"> Seguro Garantido<br>

            </div>
            <div class="form-group">

                <input asp-action="Orcar" type="submit" value="Solicitar Orçamento"/>
            </div>


        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Home</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ParqueWeb/Views/Compra/Orcar.cshtml
@model IEnumerable<ParqueBLL.Passaporte>

@{
    ViewBag.Title = "Orçamento";
}
<h1>Orçamento</h1>

<h4>Passaporte</h4>
<hr />
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.NomeCliente)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.NroDias)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DataInicial)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ValorTotal)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.NomeCliente)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.NroDias)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.DataInicial)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ValorTotal)
                </td>
            </tr>
        }
    </tbody>
</table>

<div>
    <a asp-action="Index">Home</a>
    <input asp-action="ConfirmaCompra" type="submit" value="Confirmar Compra" />
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ParqueWeb/Views/Entrada/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

ParqueWeb/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

ParqueWeb/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PARQUE</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha256-eSi1q2PG6J7g7ib17yAaWMcrr5GrtohYChqibrV7PBE=" />
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-dark border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-controller="Compra" asp-action="Index">Comprar Ingresso</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="navbar-brand" asp-controller="Entrada" asp-action="Index">Entrar</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-controller="Administrador" asp-action="Index">Administrador</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2019 - Movie App - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha256-E/V4cWE4qvAeO5MOhjtGtqDzPndRO1LBk8lJ/PR7CA4=">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>